### ISSUE TITLE
Provide cmdline option to disable update check

### ISSUE THREAD

**Issue by ta13579** [Rdiger-36/StudioBridge#4]
I am running your app on a air gapped network that isn't connected to the internet by default (corporate firewall).  It would be nice to to have an optional cmdline argument that will disable this update check.

Also, just wanted to say your app is great. It allows me to connect my printer to BambuStudio and I'm able to use the printer in (LAN mode) from a different air gapped VLAN. Thanks for creating it. =]

Command:
`
$ ./java.exe -jar StudioBridge.jar
`

Exception:
`
java.net.ConnectException: Connection timed out: connect
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
        at rdiger36.StudioBridge.Update.getVersion(Update.java:78)
        at rdiger36.StudioBridge.Update.checkVersion(Update.java:27)
        at rdiger36.StudioBridge.MainMenu.<init>(MainMenu.java:414)
        at rdiger36.StudioBridge.MainMenu$1.run(MainMenu.java:63)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

**Comment by ta13579** [comment]
Also, just wanted to say your app is great. It allows me to connect my printer to Bambu and I'm able to use the printer in LAN mode only from a different air gapped VLAN.  Thanks for creating it. =]

**Comment by Rdiger-36** [comment]
Hello @ta13579 , thank you very much for your feedback! I'm glad to hear that the app is working smoothly for you and that you like it.
Of course I can add a feature that skips the update check on startup.
I'll implement and test this later today and let you know afterwards

**Comment by Rdiger-36** [comment]
Hi @ta13579 , the new update is now available. Just add --noupdate as an argument and you skip the update process

**Comment by ta13579** [comment]
Thank you @Rdiger-36 .  Works perfectly
